name: Build, Test and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build . -t wordpress

    - name: Test Docker image
      run: docker run wordpress

    - name: Push Docker image
      uses: docker/push-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_PASSWORD }}
        password: ${{ secrets.DOCKERHUB_USERNAME }}
        repository: boudun/wordpress

